export const ADMIN_REQUEST = 'ADMIN_REQUEST';
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const ADMIN_FAILUER = 'ADMIN_FAILUER';

export const STUDENT_REQUEST = 'STUDENT_REQUEST';
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS';
export const STUDENT_FAILUER = 'STUDENT_FAILUER';

export const SCHOOL_REQUEST = 'SCHOOL_REQUEST';
export const SCHOOL_SUCCESS = 'SCHOOL_SUCCESS';
export const SCHOOL_FAILUER = 'SCHOOL_FAILUER';

export const TEACHER_REQUEST = 'TEACHER_REQUEST';
export const TEACHER_SUCCESS = 'TEACHER_SUCCESS';
export const TEACHER_FAILUER = 'TEACHER_FAILUER';


export const LOADER_SUCCESS = 'LOADER_SUCCESS';

export const CLASS_DIVISION_REQUEST = 'CLASS_DIVISION_REQUEST';
export const CLASS_DIVISION_SUCCESS = 'CLASS_DIVISION_SUCCESS';
export const CLASS_DIVISION_FAILUER = 'CLASS_DIVISION_FAILUER';

export const CLASS_TEACHER_REQUEST = 'CLASS_TEACHER_REQUEST';
export const CLASS_TEACHER_SUCCESS = 'CLASS_TEACHER_SUCCESS';
export const CLASS_TEACHER_FAILUER = 'CLASS_TEACHER_FAILUER';

export const TEACHER_CLASS_WORK_REQUEST = 'TEACHER_CLASS_WORK_REQUEST';
export const TEACHER_CLASS_WORK_SUCCESS = 'TEACHER_CLASS_WORK_SUCCESS';
export const TEACHER_CLASS_WORK_FAILUER = 'TEACHER_CLASS_WORK_FAILUER';

export const ASSIGNMENT_REQUEST = 'ASSIGNMENT_REQUEST';
export const ASSIGNMENT_SUCCESS = 'ASSIGNMENT_SUCCESS';
export const ASSIGNMENT_FAILUER = 'ASSIGNMENT_FAILUER';

export const NOTICE_REQUEST = 'NOTICE_REQUEST';
export const NOTICE_SUCCESS = 'NOTICE_SUCCESS';
export const NOTICE_FAILUER = 'NOTICE_FAILUER';


export const Add_ACTIVITY_PHOTO = "Add_ACTIVITY_PHOTO"
export const GET_ACTIVITY_PHOTO = "GET_ACTIVITY_PHOTO"
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY'

